# Generated by Django 3.1 on 2020-10-01 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0003_auto_20200825_0741'),
        ('journal', '0003_auto_20200821_1130'),
    ]

    operations = [
    ]
