# Generated by Django 3.1 on 2020-08-11 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_apikey'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ApiKey',
        ),
    ]
