# Generated by Django 3.1 on 2020-08-11 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_userapikey'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userapikey',
            options={'ordering': ('-created',), 'verbose_name': 'API key', 'verbose_name_plural': 'API keys'},
        ),
    ]
