# Generated by Django 3.1 on 2020-08-13 15:11

from django.db import models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20200813_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='target',
            name='carbohydrate',
            field=models.FloatField(null=True, blank=True),
        ),
        migrations.AlterField(
            model_name='target',
            name='fat',
            field=models.FloatField(null=True, blank=True),
        ),
        migrations.AlterField(
            model_name='target',
            name='fiber',
            field=models.FloatField(null=True, blank=True),
        ),
        migrations.AlterField(
            model_name='target',
            name='protein',
            field=models.FloatField(null=True, blank=True),
        ),
        migrations.AlterField(
            model_name='target',
            name='salt',
            field=models.FloatField(null=True, blank=True),
        ),
        migrations.AlterField(
            model_name='target',
            name='sugar',
            field=models.FloatField(null=True, blank=True),
        ),
    ]
