# Generated by Django 3.1 on 2020-08-14 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20200813_1511'),
        ('users', '0002_auto_20200814_1037'),
        ('users', '0008_auto_20200814_0606'),
    ]

    operations = [
    ]
