# Generated by Django 3.1 on 2020-08-14 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_merge_20200814_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='target',
            name='carbohydrate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='target',
            name='fat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='target',
            name='fiber',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='target',
            name='protein',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='target',
            name='salt',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='target',
            name='sugar',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
