# Generated by Django 3.1 on 2020-08-14 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calorie_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodjournal',
            name='food',
        ),
        migrations.RemoveField(
            model_name='foodjournal',
            name='user',
        ),
        migrations.AlterField(
            model_name='activity',
            name='category',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Category', to='calorie_api.activitycategory'),
        ),
        migrations.AlterField(
            model_name='food',
            name='category',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Category', to='calorie_api.foodcategory'),
        ),
        migrations.AlterField(
            model_name='food',
            name='portions',
            field=models.ManyToManyField(blank=True, related_name='Portions', to='calorie_api.FoodPortion'),
        ),
        migrations.DeleteModel(
            name='ActivityJournal',
        ),
        migrations.DeleteModel(
            name='FoodJournal',
        ),
    ]
