# Generated by Django 3.1 on 2020-08-17 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calorie_api', '0002_auto_20200814_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodcategory',
            name='uid',
            field=models.IntegerField(default=None),
        ),
    ]
