# Generated by Django 3.1 on 2020-08-17 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calorie_api', '0003_foodcategory_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodcategory',
            name='uid',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
