# Generated by Django 3.1 on 2020-08-17 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calorie_api', '0004_auto_20200817_0620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='is_public',
            field=models.BooleanField(default=True, verbose_name='Is public'),
        ),
        migrations.AlterField(
            model_name='activitycategory',
            name='is_public',
            field=models.BooleanField(default=True, verbose_name='Is public'),
        ),
        migrations.AlterField(
            model_name='food',
            name='is_public',
            field=models.BooleanField(default=True, verbose_name='Is public'),
        ),
        migrations.AlterField(
            model_name='foodcategory',
            name='is_public',
            field=models.BooleanField(default=True, verbose_name='Is public'),
        ),
        migrations.AlterField(
            model_name='foodportion',
            name='is_public',
            field=models.BooleanField(default=True, verbose_name='Is public'),
        ),
    ]
