# Generated by Django 3.1 on 2020-08-17 07:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calorie_api', '0005_auto_20200817_0701'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='uid',
            field=models.CharField(default=None, max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='activitycategory',
            name='uid',
            field=models.CharField(default=None, max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='food',
            name='uid',
            field=models.CharField(default=None, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='carbohydrate',
            field=models.FloatField(blank=True, default=0.0, null=True, validators=[django.core.validators.MinValueValidator(limit_value=0)], verbose_name='Carbohydrate (gr)'),
        ),
        migrations.AlterField(
            model_name='food',
            name='energy',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(limit_value=0)], verbose_name='Energy (kcal)'),
        ),
        migrations.AlterField(
            model_name='food',
            name='fat',
            field=models.FloatField(blank=True, default=0.0, null=True, validators=[django.core.validators.MinValueValidator(limit_value=0)], verbose_name='Fat (gr)'),
        ),
        migrations.AlterField(
            model_name='food',
            name='fiber',
            field=models.FloatField(blank=True, default=0.0, null=True, validators=[django.core.validators.MinValueValidator(limit_value=0)], verbose_name='Fiber (gr)'),
        ),
        migrations.AlterField(
            model_name='food',
            name='protein',
            field=models.FloatField(blank=True, default=0.0, null=True, validators=[django.core.validators.MinValueValidator(limit_value=0)], verbose_name='Protein (gr)'),
        ),
        migrations.AlterField(
            model_name='food',
            name='salt',
            field=models.FloatField(blank=True, default=0.0, null=True, validators=[django.core.validators.MinValueValidator(limit_value=0)], verbose_name='Salt (gr)'),
        ),
        migrations.AlterField(
            model_name='food',
            name='sugar',
            field=models.FloatField(blank=True, default=0.0, null=True, validators=[django.core.validators.MinValueValidator(limit_value=0)], verbose_name='Sugar (gr)'),
        ),
        migrations.AlterField(
            model_name='foodcategory',
            name='uid',
            field=models.CharField(default=None, max_length=50, unique=True),
        ),
    ]
