# Generated by Django 3.1 on 2020-08-17 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calorie_api', '0006_auto_20200817_0737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='uid',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='activitycategory',
            name='uid',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='uid',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='foodcategory',
            name='uid',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
