# Generated by Django 3.1 on 2020-08-17 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calorie_api', '0007_auto_20200817_0740'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='uid',
        ),
        migrations.RemoveField(
            model_name='activitycategory',
            name='uid',
        ),
    ]
