# Generated by Django 3.1 on 2020-08-17 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calorie_api', '0009_auto_20200817_0744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='uid',
            field=models.CharField(default=None, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='foodcategory',
            name='uid',
            field=models.CharField(default=None, max_length=50, unique=True),
        ),
    ]
