# Generated by Django 3.1 on 2020-08-17 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calorie_api', '0010_auto_20200817_0745'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='uid',
            field=models.CharField(default=None, max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='activitycategory',
            name='uid',
            field=models.CharField(default=None, max_length=50, unique=True),
        ),
    ]
