# Generated by Django 3.1 on 2020-08-17 12:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calorie_api', '0011_auto_20200817_0745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='energy',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(limit_value=0)], verbose_name='Energy (kcal/kg/min)'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='title',
            field=models.CharField(max_length=128, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='activitycategory',
            name='title',
            field=models.CharField(max_length=128, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='food',
            name='title',
            field=models.CharField(max_length=128, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='foodcategory',
            name='title',
            field=models.CharField(max_length=128, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='foodportion',
            name='title',
            field=models.CharField(max_length=128, verbose_name='Title'),
        ),
    ]
