# Generated by Django 3.1 on 2020-08-17 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calorie_api', '0012_auto_20200817_1237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='category',
        ),
        migrations.DeleteModel(
            name='ActivityCategory',
        ),
    ]
